/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://b3lisscobngqxixdy5n2jp5bcm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4mxcamptujd6rbptem33tnhlbq",
    "aws_cognito_identity_pool_id": "us-east-2:17fbd2a6-795e-4c5f-b95d-f2621565b977",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_snQlHYOXN",
    "aws_user_pools_web_client_id": "4rjveg1t8fq0kp92lfiahuv3pg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "yelp3-20230405203732-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://yelp3-20230405203732-hostingbucket-dev.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
